# Generated by Django 5.0.6 on 2024-11-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spl_banlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banaction',
            name='banaction_summary',
            field=models.TextField(blank=True, help_text='A summary which should include a description of the incident that led to the ban', max_length=255, verbose_name='action summary'),
        ),
        migrations.AlterField(
            model_name='banaction',
            name='title',
            field=models.CharField(blank=True, help_text='A title for the banaction (ex, Benjamin, three weeks, disruptive behavior )', max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='bannee',
            name='description',
            field=models.TextField(blank=True, help_text='A description of the bannee', verbose_name='description'),
        ),
    ]
