# Generated by Django 5.0.6 on 2024-11-18 11:20

import datetime
import django.db.models.deletion
import spl_banlist.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spl_banlist', '0002_customer_remove_banaction_bannee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banaction',
            options={'ordering': ('-expiration',)},
        ),
        migrations.RemoveField(
            model_name='banaction',
            name='banaction_summary',
        ),
        migrations.RemoveField(
            model_name='banaction',
            name='when_lifted',
        ),
        migrations.RemoveField(
            model_name='banaction',
            name='when_submitted',
        ),
        migrations.AddField(
            model_name='banaction',
            name='expiration',
            field=models.DateField(default=spl_banlist.models.seven_days_hence, help_text='The date as of which the customer is no longer banned. For an indefinite ban, set the date far in the future (ie ten years)', verbose_name='expiration'),
        ),
        migrations.AddField(
            model_name='banaction',
            name='start_date',
            field=models.DateField(default=datetime.date.today, help_text='The date and time that the ban began or will begin', verbose_name='start date'),
        ),
        migrations.AddField(
            model_name='banaction',
            name='summary',
            field=models.TextField(blank=True, help_text='A summary which should include a description of the incident that led to the ban', max_length=255, verbose_name='summary'),
        ),
        migrations.AlterField(
            model_name='banaction',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='The customer for whom the ban is applies', null=True, on_delete=django.db.models.deletion.SET_NULL, to='spl_banlist.customer'),
        ),
        migrations.AlterField(
            model_name='banaction',
            name='submitter',
            field=models.ForeignKey(blank=True, help_text='The user who entered this information', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='submitter'),
        ),
        migrations.AlterField(
            model_name='banaction',
            name='title',
            field=models.CharField(blank=True, help_text="A title for the ban (ex, Benjamin, three weeks, disruptive behavior ).  This is optional. The date and customer's name will be used if left blank", max_length=255, verbose_name='title'),
        ),
        migrations.DeleteModel(
            name='Banactionnote',
        ),
    ]
