# Generated by Django 5.0.6 on 2024-11-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spl_banlist', '0002_alter_banaction_banaction_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banneephoto',
            name='content',
        ),
        migrations.AddField(
            model_name='banneephoto',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='If this is the primary photo for this bannee', verbose_name='is primary'),
        ),
        migrations.AlterField(
            model_name='banaction',
            name='when_lifted',
            field=models.DateField(blank=True, help_text='The date that the banaction is lifted', null=True, verbose_name='when lifted'),
        ),
    ]
