# Generated by Django 5.0.6 on 2024-11-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spl_banlist', '0003_alter_banaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banaction',
            name='title',
            field=models.CharField(blank=True, help_text='A title for the ban. This is optional.  Leave blank to accept the default display', max_length=255, verbose_name='title'),
        ),
    ]
